### ISSUE TITLE
ToDo's towards a usable library

### ISSUE THREAD

**Issue by prisae** [emsig/libdlf#1]
These are the principal ToDo's to get to a usable state. Additional "ToDo's" are tracked in #2, #3, and #4.

- [ ] Write *Digital Linear Filters* section, with references to most important articles.
- [ ] Write *What is `libdlf`*.
- [ ] Add code examples of its usage.
- [x] Add CI test to validate json file. #12
- [x] Add CI tests for all filters.
- [x] Add automatic Zenodo and badge. https://github.com/emsig/libdlf/commit/528aa3bdef6f587d9ed130037e9399768c7027d4

**Comment by kerrykey** [comment]
We might think about a **Recommended Applications** section  where we could document application experiences with the filters. I know I've found modeling applications where one filter is great and another not so good, and then other modeling scenarios where the opposite is true.

**Comment by prisae** [comment]
Sounds great @kerrykey , feel free to start such a section. Not sure if moving to a more dedicated documentation (Sphinx or another tool) might be better at some point (also for nicer maths etc). But I feel that for the moment the simple README is OK.

**Comment by prisae** [comment]
I added a simple test for all filters to the Python-GHA (`.github/workflows/linux_python.yml`). That should be enough. We should test new filters visually for a more extensive model, but that has only to be done ONCE, when adding a filter.
