### ISSUE TITLE
Add filters

### ISSUE THREAD

**Issue by prisae** [emsig/libdlf#2]
# Filters and permissions

This is an issue to keep track of filters we would like to add. At the same time, we can track here that authors have given permissions to add their filters under the CC-BY-4.0 license.

- [x] Hankel filter (801pt) of Anderson, TOMS, 1982 #13
- [x] Hankel filter (J0 61, 120; J1 47, 140 pt) of Guptasarma and Singh, GP, 1997 #25
- [x] Hankel filters (61pt, 121pt, 241pt) of Kong, Geophysical Prospecting, 2007 #11 
- [x] Hankel filters (101pt, 201pt, 401pt) and Fourier filters (81pt, 241pt, 601pt) of Key, Geophysics, 2009 #5
- [x] Hankel filters (51pt, 101pt, 201pt) and Fourier filters (101pt, 201pt) of Key, Geophysics, 2012 #5
- [x] Hankel filter (201 pt, 2001pt) of Werthmüller et al., Geophysics, 2019 #5
- [x] Fourier filter (50pt) of Grayver et al., Journal of Geophysical Research: Space Physics, 2021 #10

**Comment by prisae** [comment]
I herewith give permission to integrate my filters under the CC-BY-4.0 license.

**Comment by prisae** [comment]
Filter from Grayver, 2021, added in #10 (PR also includes Alexander's consent).

**Comment by prisae** [comment]
Filters from Kong, 2007, added in #11 (PR also includes Kong's consent).

**Comment by kerrykey** [comment]
I give permission to integrate my filters under the CC-BY-4.0 license.
